
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erms_application_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5437:5432"

volumes:
  pgdata:
