"""db_change migration

Revision ID: ae1deb7f1608
Revises: 
Create Date: 2025-06-19 23:07:38.489999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae1deb7f1608'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('seniority_level', sa.Enum('JUNIOR', 'MID', 'SENIOR', name='senioritylevel'), nullable=False),
    sa.Column('role', sa.Enum('ENGINEER', 'MANAGER', name='userrole'), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('password_updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_status', sa.Enum('PLANNING', 'ACTIVE', 'COMPLETED', name='projectstatus'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('assignment_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('end_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('engineer_id', sa.UUID(), nullable=False),
    sa.Column('allocation_percentage', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
